version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: db_app
    volumes:
      - ./sql/images:/sql_images
      - database_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - 8002:3306
    networks:
      - app-network

  server:
    image: nginx:alpine
    container_name: nginx_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - app-network

  php-fpm:
    build:
      dockerfile: docker/php/Dockerfile
    container_name: php_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php-ini-override.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
    networks:
      - app-network

networks:
  app-network:

volumes:
  database_storage:
